"""initial migration

Revision ID: 7c795729c3d1
Revises: 
Create Date: 2022-06-29 16:17:11.835263

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.services.database.models import OperationStatus


# revision identifiers, used by Alembic.
revision = '7c795729c3d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sqlalchemy_utils.types.password.PasswordType(max_length=128), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.CheckConstraint('balance >= 0', name='check_balance_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('transactions_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('is_declined', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum(OperationStatus, name='operation status'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_history_id'), 'transactions_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_history_id'), table_name='transactions_history')
    op.drop_table('transactions_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
